# Generated by Django 5.1.1 on 2024-09-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carbrand_alter_carservicerequest_car_brand_carmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(choices=[('audi', 'Audi'), ('mercedes', 'Mercedes'), ('lamborghini', 'Lamborghini'), ('bmw', 'Bmw'), ('porsche', 'Porsche'), ('toyota', 'Toyota'), ('maruti', 'Maruti'), ('sujuki', 'Sujuki'), ('nissan', 'Nissan'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('volkswagen', 'Volkswagen'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mazda', 'Mazda'), ('lexus', 'Lexus')], max_length=50),
        ),
    ]
